#!/bin/bash
#
# This program is free software. It comes without any warranty, to the extent
# permitted by applicable law. You can redistribute it and/or modify it under
# the terms of the Do What The Fuck You Want To Public License, Version 2, as
# published by Sam Hocevar. See WTFPL.txt or http://www.wtfpl.net/ for more
# details.

export start_time="$(date "+%Y-%m-%d_%H:%M:%S")"

if ! self_file=$(readlink -m "${0}"); then
  echo "ERROR:  Failed to find myself!" >&2
  exit 1
fi

self_name=$(basename "${self_file}")
self_call_name=$(basename "${0}")
self_path=$(echo "${self_file}" | sed 's/\/[^/]*$//')

cd "${self_path}" || {
  echo "ERROR:  Failed to go home:  ${self_path}" >&2
  exit 1
}

if test $# -lt 2; then
  echo -e "ERROR:  Usage:\n  ${self_call_name} <profile> <action>" >&2
  exit 1
fi

if ! source lib/initialize.sh; then
  echo "ERROR:  Failed to load Android Imaging Toolkit." >&2
  exit 1
fi

initialize || {
  echo "ERROR:  Failed to initiallize Android Imaging Toolkit." >&2
  exit 1
}

profile_name="${1}"
shift

module="${1}"
shift

function main {
  profile_file="profiles/${profile_name}.sh"
  . "${profile_file}" \
    || fail "Failed to load profile:  ${profile}"

  device_id=$(device_id)
  test "${device_id}" == "${expected_device_id}" \
    || fail "Device id:  '${device_id}'  Expected:  '${expected_device_id}'"

  image_file="image_${device_code_name}.zip"
  latest_twrp_image_link=$(latest_twrp_image_link)
  twrp_image_file=$(echo "${latest_twrp_image_link}" | sed 's/^.*\///')

  if test -f modules/"${module}".sh; then
    module_file="$(readlink -m modules/"${module}".sh)" \
      || fail "Failed to get full path to:  modules/${modules}.sh"
  else
    fail "No such module:  ${module}"
  fi

  cd "${work_dir}" \
    || fail "Failed to enter directory:  ${work_dir}"

  . "${module_file}" "${@}" \
    || fail "Failed to source:  ${module_file}"
}

main
