#!/bin/bash
#
# This program is free software. It comes without any warranty, to the extent
# permitted by applicable law. You can redistribute it and/or modify it under
# the terms of the Do What The Fuck You Want To Public License, Version 2, as
# published by Sam Hocevar. See WTFPL.txt or http://www.wtfpl.net/ for more
# details.

source settings.sh

if test $# -lt 1; then
  echo Specify a profile.>&2
  exit 1
fi
profile="${1}"

source profiles/"${profile}".sh

source lib/ait.sh

function main {
  test 1 -eq $start_device_count        || fail "I expect one device, but found ${start_device_count} (${start_adb_count} adb and ${start_fastboot_count} fastboot)."
  #backup_data                           || fail "Failed to backup data."
  #download_latest_stock_image           || fail "Failed to download stock image."
  download_latest_twrp_image            || fail "Failed to download TWRP recovery image."
  #download_superuser                    || fail "Failed to download superuser."
  #unpack_image                          || fail "Failed to unpack image."
  #install_image                         || fail "Failed to install image."
  install_twrp_image                    || fail "Failed to install TWRP recovery image."
  install_superuser                     || fail "Failed to install superuser."
  # Leave fastboot.
  reboot_from_device_to_device          || fail "Failed to reboot from adb to adb."
  #restore_data                          || fail "Failed to restore application data."
  output                                "Success!"
}


if test '-h' == "${1}" || test '--help' == "${1}"; then
  requirements                          || fail "Failed to state requirements."
else
  main
fi
